pipeline {
    agent any

    environment {
        IMAGE = "gaganaraj2001/springboot-k8s-app"
    }

    stages {

        stage('Build JAR') {
            steps {
                dir('sak_group_spring_app-main') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('sak_group_spring_app-main') {
                    sh 'docker build -t $IMAGE:latest .'
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                      docker push $IMAGE:latest
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f sak_group_spring_app-main/kube_deploy/ -n dev'
            }
        }
    }
}
